# check=error=true

ARG DEBIAN_DIST_TAG="nonexistent"
ARG S6_OVERLAY_VERSION="nonexistent"

FROM docker.io/lqhuang/artifact-s6-overlay:${S6_OVERLAY_VERSION} AS s6-stage

FROM docker.io/debian:${DEBIAN_DIST_TAG}

COPY --from=s6-stage / /

ENV LANG="C.UTF-8"

ENTRYPOINT ["/init"]

CMD ["sh"]
