# check=error=true

ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NONINTERACTIVE_SEEN="true"
ARG DEBIAN_DIST_TAG="latest-slim"

ARG S6_OVERLAY_VERSION="nonexistent"

FROM lqhuang/s6-dist:${S6_OVERLAY_VERSION} AS s6-stage

FROM debian:${DEBIAN_DIST_TAG}

COPY --from=s6-stage /opt/s6-rootfs /

ENV LANG="C.UTF-8"

ENTRYPOINT ["/init"]
