# check=error=true

ARG DEBIAN_DIST_TAG="nonexistent"
ARG S6_OVERLAY_VERSION="nonexistent"

FROM ghcr.io/lqhuang/shiho/s6-overlay:${S6_OVERLAY_VERSION} AS shiho-s6-overlay

FROM docker.io/debian:${DEBIAN_DIST_TAG}

COPY --from=shiho-s6-overlay /opt/cellar/s6-overlay/ /

ENV LANG="C.UTF-8"

ENTRYPOINT ["/init"]

CMD ["sh"]
