# check=error=true

ARG ALPINE_DIST_TAG="nonexistent"
ARG S6_OVERLAY_VERSION="nonexistent"

FROM docker.io/lqhuang/artifact-s6-overlay:${S6_OVERLAY_VERSION} AS s6-stage

FROM docker.io/alpine:${ALPINE_DIST_TAG}

COPY --from=s6-stage / /

ENV LANG="C.UTF-8"

ENTRYPOINT ["/init"]

CMD ["sh"]
