# check=error=true

ARG MISE_PREFIX="/opt/cellar/mise"

FROM alpine:3.22 AS stage

ARG MISE_PREFIX
ARG MISE_VERSION
# `MISE_INSTALL_PATH` is a option for https://mise.run script
ARG MISE_INSTALL_PATH="${MISE_PREFIX}/bin/mise"

RUN apk add --no-cache ca-certificates curl xz gzip zstd ripgrep

RUN <<-EOS
    set -eux -o pipefail
    echo "Installing mise version ${MISE_VERSION}"
    echo "Installing mise to ${MISE_INSTALL_PATH}"
    mkdir -p "$(dirname "${MISE_INSTALL_PATH}")"
    curl -f#SL https://mise.run | sh
    ${MISE_INSTALL_PATH} --version
EOS

FROM scratch

ARG MISE_PREFIX

COPY --from=stage "${MISE_PREFIX}" "${MISE_PREFIX}"
